apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: swagger-aggregator
build:
  artifacts:
    - image: swagger-aggregator
  local:
    useDockerCLI: false
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      - config/deployment.yml
